// Created with https://tomeko.net/online_tools/cpp_text_escape.php?lang=en
const char* indexHTML PROGMEM = {"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title>Auto-coffee</title>\n"
"    <style>\n"
"        .container {\n"
"            height: 100vh;\n"
"            width: 100vw;\n"
"            text-align:center;\n"
"        }\n"
"    \n"
"        .button.make {\n"
"            margin: auto auto;\n"
"            height: 50vh;\n"
"            width: 50vw;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1 class=\"title\">Automatic coffee</h1>\n"
"        <form action=\"/action\" method=\"post\">\n"
"            <button class=\"button make\">Make</button>\n"
"        </form>\n"
"    </div>\n"
"</body>\n"
"</html>"};
