char *index =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"UTF-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"    <title>AutoCoffee</title>\n"
"    <style>\n"
"      body {\n"
"        margin: 0;\n"
"        padding: 0;\n"
"        font-size: 1.8em;\n"
"        width: 100%;\n"
"        height: 100vh;\n"
"      }\n"
"\n"
"      .content {\n"
"        max-width: 90%;\n"
"        margin: auto;\n"
"      }\n"
"\n"
"      .status {\n"
"        text-align: center;\n"
"        padding: 1em 0;\n"
"        margin-top: 1em;\n"
"        background-color: orange;\n"
"      }\n"
"\n"
"      .actions {\n"
"        margin: 2em auto;\n"
"        text-align: center;\n"
"      }\n"
"\n"
"      .actions button {\n"
"        font-size: 0.8em;\n"
"        width: 6em;\n"
"        height: 2em;\n"
"        margin: 0.5em 1.5em;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"content\">\n"
"      <div class=\"status\">\n"
"        Waiting...\n"
"      </div>\n"
"      <div class=\"actions\">\n"
"        <button>\n"
"          Start\n"
"        </button>\n"
"        <button>\n"
"          Start 2\n"
"        </button>\n"
"        <button>\n"
"          Start 3\n"
"        </button>\n"
"      </div>\n"
"    </div>\n"
"  </body>\n"
"</html>\n"
;