char *index =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"  <head>"
"    <meta charset=\"UTF-8\" />"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
"    <title>AutoCoffee</title>"
"    <style>"
"      body {"
"        margin: 0;"
"        padding: 0;"
"        font-size: 1.8em;"
"        width: 100%;"
"        height: 100vh;"
"      }"
""
"      .content {"
"        max-width: 90%;"
"        margin: auto;"
"      }"
""
"      .status {"
"        text-align: center;"
"        padding: 1em 0;"
"        margin-top: 1em;"
"        background-color: orange;"
"      }"
""
"      .actions {"
"        margin: 2em auto;"
"        text-align: center;"
"      }"
""
"      .actions button {"
"        font-size: 0.8em;"
"        width: 6em;"
"        height: 2em;"
"        margin: 0.5em 1.5em;"
"      }"
"    </style>"
"  </head>"
"  <body>"
"    <div class=\"content\">"
"      <div class=\"status\">"
"        Waiting..."
"      </div>"
"      <div class=\"actions\">"
"        <button>"
"          Start"
"        </button>"
"        <button>"
"          Start 2"
"        </button>"
"        <button>"
"          Start 3"
"        </button>"
"      </div>"
"    </div>"
"  </body>"
"</html>"
;